logging:
       level:
            org:
                hibernate:
                          SQL: debug
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect:  org.hibernate.dialect.H2Dialect

